// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://jingdezhen.test/terms",
        "contact": {
            "name": "Jingdezhen Ceramics Platform Team"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cart": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the signed-in user's cart, enriched with display info\nfor the requested locale. Optional ?currency= adds presentment\ntotals + per-line presentment prices (USD/EUR/GBP; FX-snapshotted).\nStock is advisory at this stage (authoritative decrement at checkout).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cart"
                ],
                "summary": "Get the current user's cart",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003caccess_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "\"en-US\"",
                        "description": "BCP 47 locale (e.g. en-US). Overrides Accept-Language.",
                        "name": "locale",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Presentment currency (USD/EUR/GBP). Adds presentment totals + per-line prices.",
                        "name": "currency",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.Cart"
                        }
                    },
                    "401": {
                        "description": "Authentication required",
                        "schema": {
                            "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cart/items": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Adds a SKU to the cart. POST is additive: the existing qty for\nthis SKU is incremented by qty (defaults to 1). A qty exceeding\navailable stock returns 409 (advisory; authoritative decrement\nis at checkout).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cart"
                ],
                "summary": "Add an item to the cart",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003caccess_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Item to add (qty optional, defaults to 1)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.AddCartItemRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created (empty body)"
                    },
                    "400": {
                        "description": "Invalid body / validation / qty \u003c 1",
                        "schema": {
                            "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication required",
                        "schema": {
                            "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "SKU not in cart or does not exist",
                        "schema": {
                            "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Quantity exceeds available stock",
                        "schema": {
                            "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Removes all listed SKUs from the cart. Returns the count removed.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cart"
                ],
                "summary": "Bulk-remove items from the cart",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003caccess_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "SKU IDs to remove (min 1)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.BulkRemoveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"removed\": \u003ccount\u003e}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Invalid body / validation (min 1 SKU ID)",
                        "schema": {
                            "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication required",
                        "schema": {
                            "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cart/items/{sku_id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Removes a SKU from the cart entirely (not a decrement).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cart"
                ],
                "summary": "Remove an item from the cart",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003caccess_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "SKU ID",
                        "name": "sku_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content (empty body)"
                    },
                    "400": {
                        "description": "Invalid SKU ID",
                        "schema": {
                            "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication required",
                        "schema": {
                            "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "SKU not in cart or does not exist",
                        "schema": {
                            "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Sets the quantity for a SKU in the cart to exactly qty (absolute,\nnot additive). A qty exceeding available stock returns 409.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cart"
                ],
                "summary": "Set a cart item's quantity",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003caccess_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "SKU ID",
                        "name": "sku_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New quantity (absolute set, must be \u003e= 1)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.UpdateCartItemRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content (empty body)"
                    },
                    "400": {
                        "description": "Invalid SKU ID / body / validation / qty \u003c 1",
                        "schema": {
                            "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication required",
                        "schema": {
                            "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "SKU not in cart or does not exist",
                        "schema": {
                            "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Quantity exceeds available stock",
                        "schema": {
                            "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/cart/merge": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Merges a guest localStorage cart (posted on login) into the\nsigned-in user's server cart. Each guest item is upserted\nadditively, capped at the SKU's stock. Returns the merged cart\n(same shape as GET /cart). Optional ?currency= adds presentment.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cart"
                ],
                "summary": "Merge a guest cart into the server cart",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003caccess_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "\"en-US\"",
                        "description": "BCP 47 locale (e.g. en-US). Overrides Accept-Language.",
                        "name": "locale",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Presentment currency (USD/EUR/GBP).",
                        "name": "currency",
                        "in": "query"
                    },
                    {
                        "description": "Guest cart items to merge",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.MergeCartRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.Cart"
                        }
                    },
                    "400": {
                        "description": "Invalid body / validation",
                        "schema": {
                            "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication required",
                        "schema": {
                            "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/catalog/categories": {
            "get": {
                "description": "Distinct categories across published products (bare strings for MVP).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog",
                    "categories"
                ],
                "summary": "List product categories",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/catalog/products": {
            "get": {
                "description": "Paginated list of published products in the requested locale.\nSupports filtering by category, artist, and tags (ANY-match).\nLocale resolution: ?locale= overrides Accept-Language.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog",
                    "products"
                ],
                "summary": "List published products",
                "parameters": [
                    {
                        "type": "string",
                        "default": "\"en-US\"",
                        "description": "BCP 47 locale (e.g. en-US). Overrides Accept-Language.",
                        "name": "locale",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Category name (exact match)",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Artist ID",
                        "name": "artist",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated canonical tag keys (ANY-match, e.g. hand-painted,celadon-glaze)",
                        "name": "tag",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number (1-based)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Page size (max 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.PaginatedResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.Product"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/catalog/products/{slug}": {
            "get": {
                "description": "Fetches a single published product by its locale-specific slug,\nwith SKUs, gallery, and tags loaded. Optional ?currency= adds\npresentment pricing to each SKU (USD/EUR/GBP; FX-snapshotted).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog",
                    "products"
                ],
                "summary": "Get a product by slug",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product slug (locale-specific)",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "\"en-US\"",
                        "description": "BCP 47 locale (e.g. en-US). Overrides Accept-Language.",
                        "name": "locale",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Presentment currency (USD/EUR/GBP). Adds ` + "`" + `price` + "`" + ` + ` + "`" + `price_currency` + "`" + ` to each SKU.",
                        "name": "currency",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.Product"
                        }
                    },
                    "400": {
                        "description": "Missing slug",
                        "schema": {
                            "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Product not found (or not published in this locale)",
                        "schema": {
                            "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/catalog/tags": {
            "get": {
                "description": "Tags attached to at least one published product, with the\nlocale-resolved display name + a product count.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog",
                    "tags"
                ],
                "summary": "List product tags (public facet)",
                "parameters": [
                    {
                        "type": "string",
                        "default": "\"en-US\"",
                        "description": "BCP 47 locale (e.g. en-US). Overrides Accept-Language.",
                        "name": "locale",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.TagWithCount"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "jingdezhen-ceramics-backend_internal_models.AddCartItemRequest": {
            "type": "object",
            "required": [
                "sku_id"
            ],
            "properties": {
                "qty": {
                    "type": "integer",
                    "minimum": 1
                },
                "sku_id": {
                    "type": "integer"
                }
            }
        },
        "jingdezhen-ceramics-backend_internal_models.BulkRemoveRequest": {
            "type": "object",
            "required": [
                "sku_ids"
            ],
            "properties": {
                "sku_ids": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "jingdezhen-ceramics-backend_internal_models.Cart": {
            "type": "object",
            "properties": {
                "currency": {
                    "description": "ISO 4217 (when ?currency=)",
                    "type": "string"
                },
                "item_count": {
                    "description": "sum of distinct SKUs (not sum of qty)",
                    "type": "integer"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.CartItem"
                    }
                },
                "total": {
                    "description": "presentment minor units (when ?currency=)",
                    "type": "integer"
                },
                "total_cny": {
                    "description": "sum of line_total_cny, minor units (fen)",
                    "type": "integer"
                }
            }
        },
        "jingdezhen-ceramics-backend_internal_models.CartItem": {
            "type": "object",
            "properties": {
                "added_at": {
                    "type": "string"
                },
                "artist_name": {
                    "type": "string"
                },
                "attributes": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "line_total": {
                    "description": "presentment minor units",
                    "type": "integer"
                },
                "line_total_cny": {
                    "description": "unit_price_cny * qty",
                    "type": "integer"
                },
                "product_id": {
                    "type": "integer"
                },
                "product_slug": {
                    "type": "string"
                },
                "product_title": {
                    "type": "string"
                },
                "qty": {
                    "type": "integer"
                },
                "sku_code": {
                    "type": "string"
                },
                "sku_id": {
                    "type": "integer"
                },
                "stock": {
                    "type": "integer"
                },
                "thumbnail_url": {
                    "type": "string"
                },
                "unit_price": {
                    "description": "Presentment-currency fields (populated when ?currency= is supplied).",
                    "type": "integer"
                },
                "unit_price_cny": {
                    "description": "minor units (fen)",
                    "type": "integer"
                },
                "weight_grams": {
                    "type": "integer"
                }
            }
        },
        "jingdezhen-ceramics-backend_internal_models.ContentStatus": {
            "type": "string",
            "enum": [
                "draft",
                "in_review",
                "published",
                "rejected"
            ],
            "x-enum-varnames": [
                "StatusDraft",
                "StatusInReview",
                "StatusPublished",
                "StatusRejected"
            ]
        },
        "jingdezhen-ceramics-backend_internal_models.ErrorResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "description": "Optional additional details",
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "jingdezhen-ceramics-backend_internal_models.MediaAsset": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "duration": {
                    "description": "seconds (videos)",
                    "type": "integer"
                },
                "height": {
                    "type": "integer"
                },
                "hls_key": {
                    "description": "transcoded HLS playlist (videos)",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "kind": {
                    "description": "image | video",
                    "type": "string"
                },
                "mime": {
                    "type": "string"
                },
                "oss_key": {
                    "type": "string"
                },
                "public_url": {
                    "description": "PublicURL resolved at read time by the storage adapter. Not in DB.",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "uploaded_by": {
                    "type": "string"
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "jingdezhen-ceramics-backend_internal_models.MergeCartItem": {
            "type": "object",
            "required": [
                "qty",
                "sku_id"
            ],
            "properties": {
                "qty": {
                    "type": "integer",
                    "minimum": 1
                },
                "sku_id": {
                    "type": "integer"
                }
            }
        },
        "jingdezhen-ceramics-backend_internal_models.MergeCartRequest": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.MergeCartItem"
                    }
                }
            }
        },
        "jingdezhen-ceramics-backend_internal_models.PaginatedResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "jingdezhen-ceramics-backend_internal_models.Product": {
            "type": "object",
            "properties": {
                "artist_id": {
                    "description": "parent: FK to artists.id",
                    "type": "integer"
                },
                "artist_name": {
                    "description": "populated by service (joined or from artist_translations)",
                    "type": "string"
                },
                "artist_slug": {
                    "description": "for cross-link to artist profile",
                    "type": "string"
                },
                "category": {
                    "description": "parent: bare string for now (dead post-media; kept for back-comat)",
                    "type": "string"
                },
                "created_at": {
                    "description": "parent",
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "display_order": {
                    "description": "parent",
                    "type": "integer"
                },
                "gallery": {
                    "description": "Gallery loaded by the service (detail view only). Empty when no\nproduct_media rows. The first item's media PublicURL is the preferred\nthumbnail; ThumbnailURL above is the fallback for back-comat.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.ProductMediaItem"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "locale": {
                    "type": "string"
                },
                "meta_description": {
                    "type": "string"
                },
                "meta_title": {
                    "type": "string"
                },
                "published_at": {
                    "type": "string"
                },
                "skus": {
                    "description": "SKUs loaded by the service (detail view only; omitted from list view).",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.SKU"
                    }
                },
                "slug": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.ContentStatus"
                },
                "tags": {
                    "description": "Tags loaded by the service (list + detail views; batch-loaded to avoid N+1).\n` + "`" + `Name` + "`" + ` is the locale-resolved display name (en-US → key fallback).",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.Tag"
                    }
                },
                "thumbnail_url": {
                    "description": "parent: primary display (dead post-media; gallery preferred)",
                    "type": "string"
                },
                "title": {
                    "description": "Translation fields.",
                    "type": "string"
                },
                "updated_at": {
                    "description": "parent",
                    "type": "string"
                }
            }
        },
        "jingdezhen-ceramics-backend_internal_models.ProductMediaItem": {
            "type": "object",
            "properties": {
                "caption": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "description": "product_media.id",
                    "type": "integer"
                },
                "media": {
                    "description": "The media asset, loaded via JOIN. Embedded so the JSON nests it.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/jingdezhen-ceramics-backend_internal_models.MediaAsset"
                        }
                    ]
                },
                "media_id": {
                    "type": "integer"
                },
                "product_id": {
                    "type": "integer"
                },
                "sort_order": {
                    "type": "integer"
                }
            }
        },
        "jingdezhen-ceramics-backend_internal_models.SKU": {
            "type": "object",
            "properties": {
                "attributes": {
                    "description": "JSONB map",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "low_stock_threshold": {
                    "type": "integer"
                },
                "price": {
                    "description": "Presentment-currency price (populated when the request carries ?currency=).\nNil when no conversion was requested. TDD §7: converted at read time from\nthe cached fx_rates, with the PRD rounding rule applied.",
                    "type": "integer"
                },
                "price_cny": {
                    "description": "minor units (fen)",
                    "type": "integer"
                },
                "price_currency": {
                    "description": "ISO 4217",
                    "type": "string"
                },
                "product_id": {
                    "type": "integer"
                },
                "sku_code": {
                    "type": "string"
                },
                "stock": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "weight_grams": {
                    "description": "packed weight",
                    "type": "integer"
                }
            }
        },
        "jingdezhen-ceramics-backend_internal_models.Tag": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "key": {
                    "type": "string"
                },
                "name": {
                    "description": "locale-resolved (COALESCE in the JOIN)",
                    "type": "string"
                }
            }
        },
        "jingdezhen-ceramics-backend_internal_models.TagWithCount": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "key": {
                    "type": "string"
                },
                "name": {
                    "description": "locale-resolved (COALESCE in the JOIN)",
                    "type": "string"
                },
                "product_count": {
                    "type": "integer"
                }
            }
        },
        "jingdezhen-ceramics-backend_internal_models.UpdateCartItemRequest": {
            "type": "object",
            "required": [
                "qty"
            ],
            "properties": {
                "qty": {
                    "type": "integer",
                    "minimum": 1
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "\"Bearer \u003caccess_token\u003e\" — JWT access token from POST /auth/login (or OAuth). Required for all /admin/* and customer-authed endpoints; omitted for public /catalog/* reads.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Jingdezhen Ceramics Platform API",
	Description:      "Internationalized culture / e-commerce / custom-travel platform for Jingdezhen ceramic art.\nBackend in Go + Fiber; money as BIGINT minor units (CNY base, USD/EUR/GBP presentment).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
