/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleAccountRouteImport } from './routes/$locale/account'
import { Route as LocaleCartRouteImport } from './routes/$locale/cart'
import { Route as LocaleCheckoutRouteImport } from './routes/$locale/checkout'
import { Route as LocaleItinerariesRouteImport } from './routes/$locale/itineraries'
import { Route as LocaleItineraryRouteImport } from './routes/$locale/itinerary'
import { Route as LocaleWishlistRouteImport } from './routes/$locale/wishlist'
import { Route as LocaleArtistsIndexRouteImport } from './routes/$locale/artists/index'
import { Route as LocaleArtistsSlugRouteImport } from './routes/$locale/artists/$slug'
import { Route as LocaleAuthLoginRouteImport } from './routes/$locale/auth/login'
import { Route as LocaleAuthSignupRouteImport } from './routes/$locale/auth/signup'
import { Route as LocaleCatalogIndexRouteImport } from './routes/$locale/catalog/index'
import { Route as LocaleCatalogSlugRouteImport } from './routes/$locale/catalog/$slug'
import { Route as LocaleCeramicstoryIndexRouteImport } from './routes/$locale/ceramicstory/index'
import { Route as LocaleCeramicstorySlugRouteImport } from './routes/$locale/ceramicstory/$slug'
import { Route as LocaleCertificatesCodeRouteImport } from './routes/$locale/certificates/$code'
import { Route as LocaleEngageIndexRouteImport } from './routes/$locale/engage/index'
import { Route as LocaleEngageSlugRouteImport } from './routes/$locale/engage/$slug'
import { Route as LocaleOrdersIndexRouteImport } from './routes/$locale/orders/index'
import { Route as LocaleOrdersIdRouteImport } from './routes/$locale/orders/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAccountRoute = LocaleAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCartRoute = LocaleCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCheckoutRoute = LocaleCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleItinerariesRoute = LocaleItinerariesRouteImport.update({
  id: '/itineraries',
  path: '/itineraries',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleItineraryRoute = LocaleItineraryRouteImport.update({
  id: '/itinerary',
  path: '/itinerary',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleWishlistRoute = LocaleWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleArtistsIndexRoute = LocaleArtistsIndexRouteImport.update({
  id: '/artists/',
  path: '/artists/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleArtistsSlugRoute = LocaleArtistsSlugRouteImport.update({
  id: '/artists/$slug',
  path: '/artists/$slug',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAuthLoginRoute = LocaleAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAuthSignupRoute = LocaleAuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCatalogIndexRoute = LocaleCatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCatalogSlugRoute = LocaleCatalogSlugRouteImport.update({
  id: '/catalog/$slug',
  path: '/catalog/$slug',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCeramicstoryIndexRoute = LocaleCeramicstoryIndexRouteImport.update({
  id: '/ceramicstory/',
  path: '/ceramicstory/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCeramicstorySlugRoute = LocaleCeramicstorySlugRouteImport.update({
  id: '/ceramicstory/$slug',
  path: '/ceramicstory/$slug',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCertificatesCodeRoute = LocaleCertificatesCodeRouteImport.update({
  id: '/certificates/$code',
  path: '/certificates/$code',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleEngageIndexRoute = LocaleEngageIndexRouteImport.update({
  id: '/engage/',
  path: '/engage/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleEngageSlugRoute = LocaleEngageSlugRouteImport.update({
  id: '/engage/$slug',
  path: '/engage/$slug',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleOrdersIndexRoute = LocaleOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleOrdersIdRoute = LocaleOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => LocaleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/account': typeof LocaleAccountRoute
  '/$locale/cart': typeof LocaleCartRoute
  '/$locale/checkout': typeof LocaleCheckoutRoute
  '/$locale/itineraries': typeof LocaleItinerariesRoute
  '/$locale/itinerary': typeof LocaleItineraryRoute
  '/$locale/wishlist': typeof LocaleWishlistRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/artists/$slug': typeof LocaleArtistsSlugRoute
  '/$locale/auth/login': typeof LocaleAuthLoginRoute
  '/$locale/auth/signup': typeof LocaleAuthSignupRoute
  '/$locale/catalog/$slug': typeof LocaleCatalogSlugRoute
  '/$locale/ceramicstory/$slug': typeof LocaleCeramicstorySlugRoute
  '/$locale/certificates/$code': typeof LocaleCertificatesCodeRoute
  '/$locale/engage/$slug': typeof LocaleEngageSlugRoute
  '/$locale/orders/$id': typeof LocaleOrdersIdRoute
  '/$locale/artists/': typeof LocaleArtistsIndexRoute
  '/$locale/catalog/': typeof LocaleCatalogIndexRoute
  '/$locale/ceramicstory/': typeof LocaleCeramicstoryIndexRoute
  '/$locale/engage/': typeof LocaleEngageIndexRoute
  '/$locale/orders/': typeof LocaleOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/account': typeof LocaleAccountRoute
  '/$locale/cart': typeof LocaleCartRoute
  '/$locale/checkout': typeof LocaleCheckoutRoute
  '/$locale/itineraries': typeof LocaleItinerariesRoute
  '/$locale/itinerary': typeof LocaleItineraryRoute
  '/$locale/wishlist': typeof LocaleWishlistRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/artists/$slug': typeof LocaleArtistsSlugRoute
  '/$locale/auth/login': typeof LocaleAuthLoginRoute
  '/$locale/auth/signup': typeof LocaleAuthSignupRoute
  '/$locale/catalog/$slug': typeof LocaleCatalogSlugRoute
  '/$locale/ceramicstory/$slug': typeof LocaleCeramicstorySlugRoute
  '/$locale/certificates/$code': typeof LocaleCertificatesCodeRoute
  '/$locale/engage/$slug': typeof LocaleEngageSlugRoute
  '/$locale/orders/$id': typeof LocaleOrdersIdRoute
  '/$locale/artists': typeof LocaleArtistsIndexRoute
  '/$locale/catalog': typeof LocaleCatalogIndexRoute
  '/$locale/ceramicstory': typeof LocaleCeramicstoryIndexRoute
  '/$locale/engage': typeof LocaleEngageIndexRoute
  '/$locale/orders': typeof LocaleOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/account': typeof LocaleAccountRoute
  '/$locale/cart': typeof LocaleCartRoute
  '/$locale/checkout': typeof LocaleCheckoutRoute
  '/$locale/itineraries': typeof LocaleItinerariesRoute
  '/$locale/itinerary': typeof LocaleItineraryRoute
  '/$locale/wishlist': typeof LocaleWishlistRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/artists/$slug': typeof LocaleArtistsSlugRoute
  '/$locale/auth/login': typeof LocaleAuthLoginRoute
  '/$locale/auth/signup': typeof LocaleAuthSignupRoute
  '/$locale/catalog/$slug': typeof LocaleCatalogSlugRoute
  '/$locale/ceramicstory/$slug': typeof LocaleCeramicstorySlugRoute
  '/$locale/certificates/$code': typeof LocaleCertificatesCodeRoute
  '/$locale/engage/$slug': typeof LocaleEngageSlugRoute
  '/$locale/orders/$id': typeof LocaleOrdersIdRoute
  '/$locale/artists/': typeof LocaleArtistsIndexRoute
  '/$locale/catalog/': typeof LocaleCatalogIndexRoute
  '/$locale/ceramicstory/': typeof LocaleCeramicstoryIndexRoute
  '/$locale/engage/': typeof LocaleEngageIndexRoute
  '/$locale/orders/': typeof LocaleOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/account'
    | '/$locale/cart'
    | '/$locale/checkout'
    | '/$locale/itineraries'
    | '/$locale/itinerary'
    | '/$locale/wishlist'
    | '/$locale/'
    | '/$locale/artists/$slug'
    | '/$locale/auth/login'
    | '/$locale/auth/signup'
    | '/$locale/catalog/$slug'
    | '/$locale/ceramicstory/$slug'
    | '/$locale/certificates/$code'
    | '/$locale/engage/$slug'
    | '/$locale/orders/$id'
    | '/$locale/artists/'
    | '/$locale/catalog/'
    | '/$locale/ceramicstory/'
    | '/$locale/engage/'
    | '/$locale/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/account'
    | '/$locale/cart'
    | '/$locale/checkout'
    | '/$locale/itineraries'
    | '/$locale/itinerary'
    | '/$locale/wishlist'
    | '/$locale'
    | '/$locale/artists/$slug'
    | '/$locale/auth/login'
    | '/$locale/auth/signup'
    | '/$locale/catalog/$slug'
    | '/$locale/ceramicstory/$slug'
    | '/$locale/certificates/$code'
    | '/$locale/engage/$slug'
    | '/$locale/orders/$id'
    | '/$locale/artists'
    | '/$locale/catalog'
    | '/$locale/ceramicstory'
    | '/$locale/engage'
    | '/$locale/orders'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/account'
    | '/$locale/cart'
    | '/$locale/checkout'
    | '/$locale/itineraries'
    | '/$locale/itinerary'
    | '/$locale/wishlist'
    | '/$locale/'
    | '/$locale/artists/$slug'
    | '/$locale/auth/login'
    | '/$locale/auth/signup'
    | '/$locale/catalog/$slug'
    | '/$locale/ceramicstory/$slug'
    | '/$locale/certificates/$code'
    | '/$locale/engage/$slug'
    | '/$locale/orders/$id'
    | '/$locale/artists/'
    | '/$locale/catalog/'
    | '/$locale/ceramicstory/'
    | '/$locale/engage/'
    | '/$locale/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/account': {
      id: '/$locale/account'
      path: '/account'
      fullPath: '/$locale/account'
      preLoaderRoute: typeof LocaleAccountRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/cart': {
      id: '/$locale/cart'
      path: '/cart'
      fullPath: '/$locale/cart'
      preLoaderRoute: typeof LocaleCartRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/checkout': {
      id: '/$locale/checkout'
      path: '/checkout'
      fullPath: '/$locale/checkout'
      preLoaderRoute: typeof LocaleCheckoutRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/itineraries': {
      id: '/$locale/itineraries'
      path: '/itineraries'
      fullPath: '/$locale/itineraries'
      preLoaderRoute: typeof LocaleItinerariesRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/itinerary': {
      id: '/$locale/itinerary'
      path: '/itinerary'
      fullPath: '/$locale/itinerary'
      preLoaderRoute: typeof LocaleItineraryRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/wishlist': {
      id: '/$locale/wishlist'
      path: '/wishlist'
      fullPath: '/$locale/wishlist'
      preLoaderRoute: typeof LocaleWishlistRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/artists/': {
      id: '/$locale/artists/'
      path: '/artists'
      fullPath: '/$locale/artists/'
      preLoaderRoute: typeof LocaleArtistsIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/artists/$slug': {
      id: '/$locale/artists/$slug'
      path: '/artists/$slug'
      fullPath: '/$locale/artists/$slug'
      preLoaderRoute: typeof LocaleArtistsSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/auth/login': {
      id: '/$locale/auth/login'
      path: '/auth/login'
      fullPath: '/$locale/auth/login'
      preLoaderRoute: typeof LocaleAuthLoginRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/auth/signup': {
      id: '/$locale/auth/signup'
      path: '/auth/signup'
      fullPath: '/$locale/auth/signup'
      preLoaderRoute: typeof LocaleAuthSignupRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/catalog/': {
      id: '/$locale/catalog/'
      path: '/catalog'
      fullPath: '/$locale/catalog/'
      preLoaderRoute: typeof LocaleCatalogIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/catalog/$slug': {
      id: '/$locale/catalog/$slug'
      path: '/catalog/$slug'
      fullPath: '/$locale/catalog/$slug'
      preLoaderRoute: typeof LocaleCatalogSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/ceramicstory/': {
      id: '/$locale/ceramicstory/'
      path: '/ceramicstory'
      fullPath: '/$locale/ceramicstory/'
      preLoaderRoute: typeof LocaleCeramicstoryIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/ceramicstory/$slug': {
      id: '/$locale/ceramicstory/$slug'
      path: '/ceramicstory/$slug'
      fullPath: '/$locale/ceramicstory/$slug'
      preLoaderRoute: typeof LocaleCeramicstorySlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/certificates/$code': {
      id: '/$locale/certificates/$code'
      path: '/certificates/$code'
      fullPath: '/$locale/certificates/$code'
      preLoaderRoute: typeof LocaleCertificatesCodeRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/engage/': {
      id: '/$locale/engage/'
      path: '/engage'
      fullPath: '/$locale/engage/'
      preLoaderRoute: typeof LocaleEngageIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/engage/$slug': {
      id: '/$locale/engage/$slug'
      path: '/engage/$slug'
      fullPath: '/$locale/engage/$slug'
      preLoaderRoute: typeof LocaleEngageSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/orders/': {
      id: '/$locale/orders/'
      path: '/orders'
      fullPath: '/$locale/orders/'
      preLoaderRoute: typeof LocaleOrdersIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/orders/$id': {
      id: '/$locale/orders/$id'
      path: '/orders/$id'
      fullPath: '/$locale/orders/$id'
      preLoaderRoute: typeof LocaleOrdersIdRouteImport
      parentRoute: typeof LocaleRoute
    }
  }
}

interface LocaleRouteChildren {
  LocaleAccountRoute: typeof LocaleAccountRoute
  LocaleCartRoute: typeof LocaleCartRoute
  LocaleCheckoutRoute: typeof LocaleCheckoutRoute
  LocaleItinerariesRoute: typeof LocaleItinerariesRoute
  LocaleItineraryRoute: typeof LocaleItineraryRoute
  LocaleWishlistRoute: typeof LocaleWishlistRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleArtistsSlugRoute: typeof LocaleArtistsSlugRoute
  LocaleAuthLoginRoute: typeof LocaleAuthLoginRoute
  LocaleAuthSignupRoute: typeof LocaleAuthSignupRoute
  LocaleCatalogSlugRoute: typeof LocaleCatalogSlugRoute
  LocaleCeramicstorySlugRoute: typeof LocaleCeramicstorySlugRoute
  LocaleCertificatesCodeRoute: typeof LocaleCertificatesCodeRoute
  LocaleEngageSlugRoute: typeof LocaleEngageSlugRoute
  LocaleOrdersIdRoute: typeof LocaleOrdersIdRoute
  LocaleArtistsIndexRoute: typeof LocaleArtistsIndexRoute
  LocaleCatalogIndexRoute: typeof LocaleCatalogIndexRoute
  LocaleCeramicstoryIndexRoute: typeof LocaleCeramicstoryIndexRoute
  LocaleEngageIndexRoute: typeof LocaleEngageIndexRoute
  LocaleOrdersIndexRoute: typeof LocaleOrdersIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAccountRoute: LocaleAccountRoute,
  LocaleCartRoute: LocaleCartRoute,
  LocaleCheckoutRoute: LocaleCheckoutRoute,
  LocaleItinerariesRoute: LocaleItinerariesRoute,
  LocaleItineraryRoute: LocaleItineraryRoute,
  LocaleWishlistRoute: LocaleWishlistRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleArtistsSlugRoute: LocaleArtistsSlugRoute,
  LocaleAuthLoginRoute: LocaleAuthLoginRoute,
  LocaleAuthSignupRoute: LocaleAuthSignupRoute,
  LocaleCatalogSlugRoute: LocaleCatalogSlugRoute,
  LocaleCeramicstorySlugRoute: LocaleCeramicstorySlugRoute,
  LocaleCertificatesCodeRoute: LocaleCertificatesCodeRoute,
  LocaleEngageSlugRoute: LocaleEngageSlugRoute,
  LocaleOrdersIdRoute: LocaleOrdersIdRoute,
  LocaleArtistsIndexRoute: LocaleArtistsIndexRoute,
  LocaleCatalogIndexRoute: LocaleCatalogIndexRoute,
  LocaleCeramicstoryIndexRoute: LocaleCeramicstoryIndexRoute,
  LocaleEngageIndexRoute: LocaleEngageIndexRoute,
  LocaleOrdersIndexRoute: LocaleOrdersIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
