/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountUserIdRouteImport } from './routes/account/$userId'
import { Route as AuthLayoutRouteImport } from './routes/auth/_layout'
import { Route as AuthActivateRouteImport } from './routes/auth/activate'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as CeramicstoryIndexRouteImport } from './routes/ceramicstory/index'
import { Route as CeramicstorySlugRouteImport } from './routes/ceramicstory/$slug'
import { Route as EngageIndexRouteImport } from './routes/engage/index'
import { Route as EngageSlugRouteImport } from './routes/engage/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountUserIdRoute = AccountUserIdRouteImport.update({
  id: '/account/$userId',
  path: '/account/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/auth/_layout',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthActivateRoute = AuthActivateRouteImport.update({
  id: '/auth/activate',
  path: '/auth/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const CeramicstoryIndexRoute = CeramicstoryIndexRouteImport.update({
  id: '/ceramicstory/',
  path: '/ceramicstory/',
  getParentRoute: () => rootRouteImport,
} as any)
const CeramicstorySlugRoute = CeramicstorySlugRouteImport.update({
  id: '/ceramicstory/$slug',
  path: '/ceramicstory/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EngageIndexRoute = EngageIndexRouteImport.update({
  id: '/engage/',
  path: '/engage/',
  getParentRoute: () => rootRouteImport,
} as any)
const EngageSlugRoute = EngageSlugRouteImport.update({
  id: '/engage/$slug',
  path: '/engage/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account/$userId': typeof AccountUserIdRoute
  '/auth': typeof AuthLayoutRoute
  '/auth/activate': typeof AuthActivateRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/ceramicstory/$slug': typeof CeramicstorySlugRoute
  '/engage/$slug': typeof EngageSlugRoute
  '/account/': typeof AccountIndexRoute
  '/ceramicstory/': typeof CeramicstoryIndexRoute
  '/engage/': typeof EngageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account/$userId': typeof AccountUserIdRoute
  '/auth': typeof AuthLayoutRoute
  '/auth/activate': typeof AuthActivateRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/ceramicstory/$slug': typeof CeramicstorySlugRoute
  '/engage/$slug': typeof EngageSlugRoute
  '/account': typeof AccountIndexRoute
  '/ceramicstory': typeof CeramicstoryIndexRoute
  '/engage': typeof EngageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account/$userId': typeof AccountUserIdRoute
  '/auth/_layout': typeof AuthLayoutRoute
  '/auth/activate': typeof AuthActivateRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/ceramicstory/$slug': typeof CeramicstorySlugRoute
  '/engage/$slug': typeof EngageSlugRoute
  '/account/': typeof AccountIndexRoute
  '/ceramicstory/': typeof CeramicstoryIndexRoute
  '/engage/': typeof EngageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account/$userId'
    | '/auth'
    | '/auth/activate'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/ceramicstory/$slug'
    | '/engage/$slug'
    | '/account/'
    | '/ceramicstory/'
    | '/engage/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account/$userId'
    | '/auth'
    | '/auth/activate'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/ceramicstory/$slug'
    | '/engage/$slug'
    | '/account'
    | '/ceramicstory'
    | '/engage'
  id:
    | '__root__'
    | '/'
    | '/account/$userId'
    | '/auth/_layout'
    | '/auth/activate'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/ceramicstory/$slug'
    | '/engage/$slug'
    | '/account/'
    | '/ceramicstory/'
    | '/engage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountUserIdRoute: typeof AccountUserIdRoute
  AuthLayoutRoute: typeof AuthLayoutRoute
  AuthActivateRoute: typeof AuthActivateRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  CeramicstorySlugRoute: typeof CeramicstorySlugRoute
  EngageSlugRoute: typeof EngageSlugRoute
  AccountIndexRoute: typeof AccountIndexRoute
  CeramicstoryIndexRoute: typeof CeramicstoryIndexRoute
  EngageIndexRoute: typeof EngageIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/$userId': {
      id: '/account/$userId'
      path: '/account/$userId'
      fullPath: '/account/$userId'
      preLoaderRoute: typeof AccountUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/_layout': {
      id: '/auth/_layout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/activate': {
      id: '/auth/activate'
      path: '/auth/activate'
      fullPath: '/auth/activate'
      preLoaderRoute: typeof AuthActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceramicstory/': {
      id: '/ceramicstory/'
      path: '/ceramicstory'
      fullPath: '/ceramicstory/'
      preLoaderRoute: typeof CeramicstoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceramicstory/$slug': {
      id: '/ceramicstory/$slug'
      path: '/ceramicstory/$slug'
      fullPath: '/ceramicstory/$slug'
      preLoaderRoute: typeof CeramicstorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engage/': {
      id: '/engage/'
      path: '/engage'
      fullPath: '/engage/'
      preLoaderRoute: typeof EngageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engage/$slug': {
      id: '/engage/$slug'
      path: '/engage/$slug'
      fullPath: '/engage/$slug'
      preLoaderRoute: typeof EngageSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountUserIdRoute: AccountUserIdRoute,
  AuthLayoutRoute: AuthLayoutRoute,
  AuthActivateRoute: AuthActivateRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  CeramicstorySlugRoute: CeramicstorySlugRoute,
  EngageSlugRoute: EngageSlugRoute,
  AccountIndexRoute: AccountIndexRoute,
  CeramicstoryIndexRoute: CeramicstoryIndexRoute,
  EngageIndexRoute: EngageIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
