/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountUserIdRouteImport } from './routes/account/$userId'
import { Route as AuthLayoutRouteImport } from './routes/auth/_layout'
import { Route as AuthActivateRouteImport } from './routes/auth/activate'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as CeramicstoryIndexRouteImport } from './routes/ceramicstory/index'
import { Route as CeramicstorySlugRouteImport } from './routes/ceramicstory/$slug'
import { Route as CourseIndexRouteImport } from './routes/course/index'
import { Route as CourseCourseIdRouteImport } from './routes/course/$courseId'
import { Route as EngageIndexRouteImport } from './routes/engage/index'
import { Route as EngageSlugRouteImport } from './routes/engage/$slug'
import { Route as ForumIndexRouteImport } from './routes/forum/index'
import { Route as ForumNewRouteImport } from './routes/forum/new'
import { Route as GalleryIndexRouteImport } from './routes/gallery/index'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio/index'
import { Route as ForumPostsPostIdRouteImport } from './routes/forum/posts/$postId'
import { Route as GalleryArtworksArtworkIdRouteImport } from './routes/gallery/artworks/$artworkId'
import { Route as PortfolioWorksWorkIdRouteImport } from './routes/portfolio/works/$workId'
import { Route as CourseCourseIdChaptersChapterIdBlocksBlockIdRouteImport } from './routes/course/$courseId/chapters/$chapterId/blocks/$blockId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountUserIdRoute = AccountUserIdRouteImport.update({
  id: '/account/$userId',
  path: '/account/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/auth/_layout',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthActivateRoute = AuthActivateRouteImport.update({
  id: '/auth/activate',
  path: '/auth/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const CeramicstoryIndexRoute = CeramicstoryIndexRouteImport.update({
  id: '/ceramicstory/',
  path: '/ceramicstory/',
  getParentRoute: () => rootRouteImport,
} as any)
const CeramicstorySlugRoute = CeramicstorySlugRouteImport.update({
  id: '/ceramicstory/$slug',
  path: '/ceramicstory/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseIndexRoute = CourseIndexRouteImport.update({
  id: '/course/',
  path: '/course/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseIdRoute = CourseCourseIdRouteImport.update({
  id: '/course/$courseId',
  path: '/course/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const EngageIndexRoute = EngageIndexRouteImport.update({
  id: '/engage/',
  path: '/engage/',
  getParentRoute: () => rootRouteImport,
} as any)
const EngageSlugRoute = EngageSlugRouteImport.update({
  id: '/engage/$slug',
  path: '/engage/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumIndexRoute = ForumIndexRouteImport.update({
  id: '/forum/',
  path: '/forum/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumNewRoute = ForumNewRouteImport.update({
  id: '/forum/new',
  path: '/forum/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumPostsPostIdRoute = ForumPostsPostIdRouteImport.update({
  id: '/forum/posts/$postId',
  path: '/forum/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryArtworksArtworkIdRoute =
  GalleryArtworksArtworkIdRouteImport.update({
    id: '/gallery/artworks/$artworkId',
    path: '/gallery/artworks/$artworkId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortfolioWorksWorkIdRoute = PortfolioWorksWorkIdRouteImport.update({
  id: '/portfolio/works/$workId',
  path: '/portfolio/works/$workId',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseIdChaptersChapterIdBlocksBlockIdRoute =
  CourseCourseIdChaptersChapterIdBlocksBlockIdRouteImport.update({
    id: '/chapters/$chapterId/blocks/$blockId',
    path: '/chapters/$chapterId/blocks/$blockId',
    getParentRoute: () => CourseCourseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account/$userId': typeof AccountUserIdRoute
  '/auth': typeof AuthLayoutRoute
  '/auth/activate': typeof AuthActivateRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/ceramicstory/$slug': typeof CeramicstorySlugRoute
  '/course/$courseId': typeof CourseCourseIdRouteWithChildren
  '/engage/$slug': typeof EngageSlugRoute
  '/forum/new': typeof ForumNewRoute
  '/account/': typeof AccountIndexRoute
  '/ceramicstory/': typeof CeramicstoryIndexRoute
  '/course/': typeof CourseIndexRoute
  '/engage/': typeof EngageIndexRoute
  '/forum/': typeof ForumIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/forum/posts/$postId': typeof ForumPostsPostIdRoute
  '/gallery/artworks/$artworkId': typeof GalleryArtworksArtworkIdRoute
  '/portfolio/works/$workId': typeof PortfolioWorksWorkIdRoute
  '/course/$courseId/chapters/$chapterId/blocks/$blockId': typeof CourseCourseIdChaptersChapterIdBlocksBlockIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account/$userId': typeof AccountUserIdRoute
  '/auth': typeof AuthLayoutRoute
  '/auth/activate': typeof AuthActivateRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/ceramicstory/$slug': typeof CeramicstorySlugRoute
  '/course/$courseId': typeof CourseCourseIdRouteWithChildren
  '/engage/$slug': typeof EngageSlugRoute
  '/forum/new': typeof ForumNewRoute
  '/account': typeof AccountIndexRoute
  '/ceramicstory': typeof CeramicstoryIndexRoute
  '/course': typeof CourseIndexRoute
  '/engage': typeof EngageIndexRoute
  '/forum': typeof ForumIndexRoute
  '/gallery': typeof GalleryIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/forum/posts/$postId': typeof ForumPostsPostIdRoute
  '/gallery/artworks/$artworkId': typeof GalleryArtworksArtworkIdRoute
  '/portfolio/works/$workId': typeof PortfolioWorksWorkIdRoute
  '/course/$courseId/chapters/$chapterId/blocks/$blockId': typeof CourseCourseIdChaptersChapterIdBlocksBlockIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account/$userId': typeof AccountUserIdRoute
  '/auth/_layout': typeof AuthLayoutRoute
  '/auth/activate': typeof AuthActivateRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/ceramicstory/$slug': typeof CeramicstorySlugRoute
  '/course/$courseId': typeof CourseCourseIdRouteWithChildren
  '/engage/$slug': typeof EngageSlugRoute
  '/forum/new': typeof ForumNewRoute
  '/account/': typeof AccountIndexRoute
  '/ceramicstory/': typeof CeramicstoryIndexRoute
  '/course/': typeof CourseIndexRoute
  '/engage/': typeof EngageIndexRoute
  '/forum/': typeof ForumIndexRoute
  '/gallery/': typeof GalleryIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/forum/posts/$postId': typeof ForumPostsPostIdRoute
  '/gallery/artworks/$artworkId': typeof GalleryArtworksArtworkIdRoute
  '/portfolio/works/$workId': typeof PortfolioWorksWorkIdRoute
  '/course/$courseId/chapters/$chapterId/blocks/$blockId': typeof CourseCourseIdChaptersChapterIdBlocksBlockIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account/$userId'
    | '/auth'
    | '/auth/activate'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/ceramicstory/$slug'
    | '/course/$courseId'
    | '/engage/$slug'
    | '/forum/new'
    | '/account/'
    | '/ceramicstory/'
    | '/course/'
    | '/engage/'
    | '/forum/'
    | '/gallery/'
    | '/portfolio/'
    | '/forum/posts/$postId'
    | '/gallery/artworks/$artworkId'
    | '/portfolio/works/$workId'
    | '/course/$courseId/chapters/$chapterId/blocks/$blockId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account/$userId'
    | '/auth'
    | '/auth/activate'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/ceramicstory/$slug'
    | '/course/$courseId'
    | '/engage/$slug'
    | '/forum/new'
    | '/account'
    | '/ceramicstory'
    | '/course'
    | '/engage'
    | '/forum'
    | '/gallery'
    | '/portfolio'
    | '/forum/posts/$postId'
    | '/gallery/artworks/$artworkId'
    | '/portfolio/works/$workId'
    | '/course/$courseId/chapters/$chapterId/blocks/$blockId'
  id:
    | '__root__'
    | '/'
    | '/account/$userId'
    | '/auth/_layout'
    | '/auth/activate'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/ceramicstory/$slug'
    | '/course/$courseId'
    | '/engage/$slug'
    | '/forum/new'
    | '/account/'
    | '/ceramicstory/'
    | '/course/'
    | '/engage/'
    | '/forum/'
    | '/gallery/'
    | '/portfolio/'
    | '/forum/posts/$postId'
    | '/gallery/artworks/$artworkId'
    | '/portfolio/works/$workId'
    | '/course/$courseId/chapters/$chapterId/blocks/$blockId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountUserIdRoute: typeof AccountUserIdRoute
  AuthLayoutRoute: typeof AuthLayoutRoute
  AuthActivateRoute: typeof AuthActivateRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  CeramicstorySlugRoute: typeof CeramicstorySlugRoute
  CourseCourseIdRoute: typeof CourseCourseIdRouteWithChildren
  EngageSlugRoute: typeof EngageSlugRoute
  ForumNewRoute: typeof ForumNewRoute
  AccountIndexRoute: typeof AccountIndexRoute
  CeramicstoryIndexRoute: typeof CeramicstoryIndexRoute
  CourseIndexRoute: typeof CourseIndexRoute
  EngageIndexRoute: typeof EngageIndexRoute
  ForumIndexRoute: typeof ForumIndexRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
  ForumPostsPostIdRoute: typeof ForumPostsPostIdRoute
  GalleryArtworksArtworkIdRoute: typeof GalleryArtworksArtworkIdRoute
  PortfolioWorksWorkIdRoute: typeof PortfolioWorksWorkIdRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/$userId': {
      id: '/account/$userId'
      path: '/account/$userId'
      fullPath: '/account/$userId'
      preLoaderRoute: typeof AccountUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/_layout': {
      id: '/auth/_layout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/activate': {
      id: '/auth/activate'
      path: '/auth/activate'
      fullPath: '/auth/activate'
      preLoaderRoute: typeof AuthActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceramicstory/': {
      id: '/ceramicstory/'
      path: '/ceramicstory'
      fullPath: '/ceramicstory/'
      preLoaderRoute: typeof CeramicstoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceramicstory/$slug': {
      id: '/ceramicstory/$slug'
      path: '/ceramicstory/$slug'
      fullPath: '/ceramicstory/$slug'
      preLoaderRoute: typeof CeramicstorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/': {
      id: '/course/'
      path: '/course'
      fullPath: '/course/'
      preLoaderRoute: typeof CourseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseId': {
      id: '/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/course/$courseId'
      preLoaderRoute: typeof CourseCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engage/': {
      id: '/engage/'
      path: '/engage'
      fullPath: '/engage/'
      preLoaderRoute: typeof EngageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engage/$slug': {
      id: '/engage/$slug'
      path: '/engage/$slug'
      fullPath: '/engage/$slug'
      preLoaderRoute: typeof EngageSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/': {
      id: '/forum/'
      path: '/forum'
      fullPath: '/forum/'
      preLoaderRoute: typeof ForumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/new': {
      id: '/forum/new'
      path: '/forum/new'
      fullPath: '/forum/new'
      preLoaderRoute: typeof ForumNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/gallery'
      fullPath: '/gallery/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/posts/$postId': {
      id: '/forum/posts/$postId'
      path: '/forum/posts/$postId'
      fullPath: '/forum/posts/$postId'
      preLoaderRoute: typeof ForumPostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/artworks/$artworkId': {
      id: '/gallery/artworks/$artworkId'
      path: '/gallery/artworks/$artworkId'
      fullPath: '/gallery/artworks/$artworkId'
      preLoaderRoute: typeof GalleryArtworksArtworkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/works/$workId': {
      id: '/portfolio/works/$workId'
      path: '/portfolio/works/$workId'
      fullPath: '/portfolio/works/$workId'
      preLoaderRoute: typeof PortfolioWorksWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseId/chapters/$chapterId/blocks/$blockId': {
      id: '/course/$courseId/chapters/$chapterId/blocks/$blockId'
      path: '/chapters/$chapterId/blocks/$blockId'
      fullPath: '/course/$courseId/chapters/$chapterId/blocks/$blockId'
      preLoaderRoute: typeof CourseCourseIdChaptersChapterIdBlocksBlockIdRouteImport
      parentRoute: typeof CourseCourseIdRoute
    }
  }
}

interface CourseCourseIdRouteChildren {
  CourseCourseIdChaptersChapterIdBlocksBlockIdRoute: typeof CourseCourseIdChaptersChapterIdBlocksBlockIdRoute
}

const CourseCourseIdRouteChildren: CourseCourseIdRouteChildren = {
  CourseCourseIdChaptersChapterIdBlocksBlockIdRoute:
    CourseCourseIdChaptersChapterIdBlocksBlockIdRoute,
}

const CourseCourseIdRouteWithChildren = CourseCourseIdRoute._addFileChildren(
  CourseCourseIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountUserIdRoute: AccountUserIdRoute,
  AuthLayoutRoute: AuthLayoutRoute,
  AuthActivateRoute: AuthActivateRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  CeramicstorySlugRoute: CeramicstorySlugRoute,
  CourseCourseIdRoute: CourseCourseIdRouteWithChildren,
  EngageSlugRoute: EngageSlugRoute,
  ForumNewRoute: ForumNewRoute,
  AccountIndexRoute: AccountIndexRoute,
  CeramicstoryIndexRoute: CeramicstoryIndexRoute,
  CourseIndexRoute: CourseIndexRoute,
  EngageIndexRoute: EngageIndexRoute,
  ForumIndexRoute: ForumIndexRoute,
  GalleryIndexRoute: GalleryIndexRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
  ForumPostsPostIdRoute: ForumPostsPostIdRoute,
  GalleryArtworksArtworkIdRoute: GalleryArtworksArtworkIdRoute,
  PortfolioWorksWorkIdRoute: PortfolioWorksWorkIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
